language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

before_install:
- rvm install "$BUILD_RUBY_VERSION"
- rvm use "$BUILD_RUBY_VERSION"
- ruby --version
- ruby -e 'require "pp"; pp RbConfig::CONFIG'

before_script:
- export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH

script:
- |
  cargo build &&
  cargo test --features=test

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  matrix:
    - BUILD_RUBY_VERSION: 2.3.7
    - BUILD_RUBY_VERSION: 2.4.4
    - BUILD_RUBY_VERSION: 2.5.1
