language: rust

os:
- linux
- osx

rust:
  - 1.25.0
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

before_install:
- rvm install "$BUILD_RUBY_VERSION"
- rvm use "$BUILD_RUBY_VERSION"
- ruby --version
- ruby -e 'require "pp"; pp RbConfig::CONFIG'
- rustc -Vv
- cargo -Vv
- mkdir -p target/debug/deps
- cp $(ruby -e 'puts File.join(RbConfig::CONFIG["libdir"], RbConfig::CONFIG["LIBRUBY_ALIASES"].split(" ").first)') target/debug/deps

before_script:
- export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH

script:
- |
  cargo build -vv &&
  cargo test -vv

after_script:
- echo "BUILD OUTPUT"
- cat target/debug/build/rutie-*/output

env:
  global:
    - RUST_BACKTRACE=full
  matrix:
    - BUILD_RUBY_VERSION: 2.3.7
    - BUILD_RUBY_VERSION: 2.4.4
    - BUILD_RUBY_VERSION: 2.5.1
